language: node_js
node_js:
- 10.17.0
install: npm rebuild node-sass && npm install
before_script: npm run dist
script: npm test
before_deploy: echo 'All unit tests passed; Successfull built distribution assets;
  Preparing to deploy Discovery Research Catalog to AWS.'
deploy:
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_DEVELOPMENT"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_DEVELOPMENT"
  region: us-east-1
  app: discovery-ui
  env: discovery-ui-shep-development
  bucket_name: elasticbeanstalk-us-east-1-224280085904
  bucket_path: discovery-ui-development
  on:
    repo: NYPL/discovery-front-end
    branch: development
- provider: elasticbeanstalk
  skip_cleanup: false
  access_key_id: "$AWS_ACCESS_KEY_ID_QA"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_QA"
  region: us-east-1
  app: discovery-ui
  env: DiscoveryUi-production
  bucket_name: elasticbeanstalk-us-east-1-946183545209
  bucket_path: discovery-ui-shep
  on:
    repo: NYPL/discovery-front-end
    branch: production
- provider: elasticbeanstalk
  skip_cleanup: false
  access_key_id: "$AWS_ACCESS_KEY_ID_QA"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_QA"
  region: us-east-1
  app: discovery-ui
  env: DiscoveryUi-10-17-qa
  bucket_name: elasticbeanstalk-us-east-1-946183545209
  bucket_path: discovery-ui-shep
  on:
    repo: NYPL/discovery-front-end
    all_branches: true
    condition: "$TRAVIS_TAG =~ ^qa-.*"
after_deploy: echo 'Successfully executed deploy trigger for Discovery Research Catalog
  on AWS'
env:
  global:
    secure: WGdFv7kbdtedn8RrH4s7klwmxRNpoDCXQ7UH9P6lX5zKCg6VCgWAO8mAFVlcbqgLZieIkjbyxSPAYnKcOXrRJfPrDD9Yd3oPSyIMPQLofJXh1ds+Q5HwP1ndB34qMj8tYGmAP2Kl/bzUAKxrrDw2J6n7TKbRgERzC2/GcI0ec1/cWv/G72Yps3uYn4gKDDdjg7sgPV0FgS3tTQ4G1p01Za0ejV+pwZsetgnALgW+VE6RwdPwzk9nwm5C7VRCbmHBxMVBPRjiuQGwOIE5Nm2nvez0XKWNlphTrjbydF7h2pw01xvZ0fxwcUo0vKQGdwATXxZgLG1xVRXjHFOZyyhi2WlZ6IfysRYbKXZBdecJ+DmVRLk1B2MWx5DFeatlm1OpIdNTAtYG0S4LZwc0zzLTYbru5n72mZgF+e93mOkji5pBlzosvc1NLFlFFOOhtR3tr5txXd2auXweWhaQZMBklZrW4xTB4cQUExGJgCktds8VI0B1lMbHXfPCJNBa+XCvjjyIWZ1E9F+yH6BfbJWafwRIFIwUZYqixO8jMMuaFISS7Kxbt0CshcGu0QnqVH/m138Gj8yKwDB4kRKZwLquj8U83fsluY5QmDIRePgvNiTdtF0gPQ9KYU64Nnt4o7CY5VB1ESJmXGdMG6EZsxX2EwKy63j+JfquUECWMnW+fO0=
